version: "0.0.27.0"
name: "Update Manager"
description: "Configurable update automations"
slug: "update-manager"
url: "https://github.com/lucaspopp0/hass-update-manager/blob/main/update-manager"
# image: ghcr.io/lucaspopp0/hass-update-manager
arch:
  - aarch64
  - amd64
  # - armhf
  - armv7
  - i386
startup: application
init: false
hassio_api: true
homeassistant_api: true
hassio_role: default
panel_title: 'Update Manager'
panel_icon: 'mdi:clock-fast'
panel_admin: false
ingress: true
ingress_port: 8124
ingress_stream: true
