components:
  schemas:
    Config:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/api/schemas/Config.json
          format: uri
          readOnly: true
          type: string
        switches:
          additionalProperties:
            $ref: '#/components/schemas/Switch'
          type: object
      required:
        - switches
      type: object
    Device:
      additionalProperties: false
      properties:
        id:
          type: string
        last_seen:
          format: date-time
          type: string
        metadata:
          additionalProperties:
            type: string
          type: object
        name:
          type: string
        rssi:
          format: int32
          type: integer
        services:
          items:
            items:
              format: int32
              minimum: 0
              type: integer
            maxItems: 4
            minItems: 4
            type:
              - array
              - "null"
          type:
            - array
            - "null"
      required:
        - id
        - name
        - rssi
        - last_seen
        - services
        - metadata
      type: object
    ErrorDetail:
      additionalProperties: false
      properties:
        location:
          description: Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
          type: string
        message:
          description: Error message text
          type: string
        value:
          description: The value at the given location
      type: object
    ErrorModel:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/api/schemas/ErrorModel.json
          format: uri
          readOnly: true
          type: string
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          examples:
            - Property foo is required but is missing.
          type: string
        errors:
          description: Optional list of individual error details
          items:
            $ref: '#/components/schemas/ErrorDetail'
          type:
            - array
            - "null"
        instance:
          description: A URI reference that identifies the specific occurrence of the problem.
          examples:
            - https://example.com/error-log/abc123
          format: uri
          type: string
        status:
          description: HTTP status code
          examples:
            - 400
          format: int64
          type: integer
        title:
          description: A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
          examples:
            - Bad Request
          type: string
        type:
          default: about:blank
          description: A URI reference to human-readable documentation for the error.
          examples:
            - https://example.com/errors/example
          format: uri
          type: string
      type: object
    Executable:
      additionalProperties: false
      properties:
        domain:
          type: string
        entityId:
          type: string
        friendlyName:
          type: string
      required:
        - domain
        - entityId
        - friendlyName
      type: object
    LayoutV4:
      additionalProperties: false
      properties:
        "1":
          type: string
        "2":
          type: string
        "3":
          type: string
        "4":
          type: string
        "5":
          type: string
        "6":
          type: string
        "7":
          type: string
        "8":
          type: string
        "off":
          type: string
        "on":
          type: string
      type: object
    LayoutV5:
      additionalProperties: false
      properties:
        "5":
          type: string
        "6":
          type: string
        "7":
          type: string
        "8":
          type: string
        flipped:
          type: boolean
        "off":
          type: string
        "on":
          type: string
        wheel-routines:
          items:
            $ref: '#/components/schemas/WheelRoutine'
          type:
            - array
            - "null"
      type: object
    LayoutV6:
      additionalProperties: false
      properties:
        "5":
          type: string
        "6":
          type: string
        "7":
          type: string
        "8":
          type: string
        flipped:
          type: boolean
        "off":
          type: string
        "on":
          type: string
        wheel-routines:
          items:
            $ref: '#/components/schemas/WheelRoutine'
          type:
            - array
            - "null"
      type: object
    LayoutV7:
      additionalProperties: false
      properties:
        "1":
          type: string
        "2":
          type: string
        "3":
          type: string
        "4":
          type: string
        "5":
          type: string
        "6":
          type: string
        "7":
          type: string
        "8":
          type: string
        flipped:
          type: boolean
        "off":
          type: string
        "on":
          type: string
      type: object
    Layouts:
      additionalProperties: false
      properties:
        v4:
          $ref: '#/components/schemas/LayoutV4'
        v5:
          $ref: '#/components/schemas/LayoutV5'
        v6:
          $ref: '#/components/schemas/LayoutV6'
        v7:
          $ref: '#/components/schemas/LayoutV7'
      type: object
    ListBLEDevicesResponseBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/api/schemas/ListBLEDevicesResponseBody.json
          format: uri
          readOnly: true
          type: string
        count:
          format: int64
          type: integer
        devices:
          additionalProperties:
            $ref: '#/components/schemas/Device'
          type: object
        scanning:
          type: boolean
      required:
        - devices
        - scanning
        - count
      type: object
    ListExecutablesResponseBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/api/schemas/ListExecutablesResponseBody.json
          format: uri
          readOnly: true
          type: string
        executables:
          additionalProperties:
            $ref: '#/components/schemas/Executable'
          type: object
      required:
        - executables
      type: object
    PostPressRequestBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/api/schemas/PostPressRequestBody.json
          format: uri
          readOnly: true
          type: string
        key:
          type: string
        layout:
          type: string
        switch:
          type: string
      required:
        - switch
        - key
        - layout
      type: object
    StartBLEScanRequestBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/api/schemas/StartBLEScanRequestBody.json
          format: uri
          readOnly: true
          type: string
        duration:
          description: 'Scan duration in seconds (default: 30, max: 300)'
          format: int64
          type: integer
      required:
        - duration
      type: object
    StartBLEScanResponseBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/api/schemas/StartBLEScanResponseBody.json
          format: uri
          readOnly: true
          type: string
        message:
          type: string
        scanning:
          type: boolean
      required:
        - message
        - scanning
      type: object
    StopBLEScanResponseBody:
      additionalProperties: false
      properties:
        $schema:
          description: A URL to the JSON Schema for this object.
          examples:
            - https://example.com/api/schemas/StopBLEScanResponseBody.json
          format: uri
          readOnly: true
          type: string
        message:
          type: string
        scanning:
          type: boolean
      required:
        - message
        - scanning
      type: object
    Switch:
      additionalProperties: false
      properties:
        layouts:
          $ref: '#/components/schemas/Layouts'
      required:
        - layouts
      type: object
    WheelRoutine:
      additionalProperties: false
      properties:
        command:
          type: string
        name:
          type: string
        rgb:
          items:
            format: int64
            type: integer
          type:
            - array
            - "null"
      required:
        - name
        - rgb
        - command
      type: object
info:
  title: Smart Switches
  version: ""
openapi: 3.1.0
paths:
  /api/ble/devices:
    get:
      description: Get a list of all BLE devices discovered during scanning
      operationId: list-ble-devices
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListBLEDevicesResponseBody'
          description: OK
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
          description: Internal Server Error
      summary: List discovered BLE devices
  /api/ble/scan/start:
    post:
      description: Start scanning for BLE devices that can act as peripherals
      operationId: start-ble-scan
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartBLEScanRequestBody'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartBLEScanResponseBody'
          description: OK
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
          description: Bad Request
        "422":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
          description: Unprocessable Entity
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
          description: Internal Server Error
      summary: Start BLE device scan
  /api/ble/scan/stop:
    post:
      description: Stop the current BLE device scan
      operationId: stop-ble-scan
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StopBLEScanResponseBody'
          description: OK
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
          description: Internal Server Error
      summary: Stop BLE device scan
  /api/config:
    get:
      operationId: get-config
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
          description: OK
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
          description: Internal Server Error
    put:
      operationId: put-config
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Config'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
          description: OK
        "422":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
          description: Unprocessable Entity
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
          description: Internal Server Error
  /api/executables:
    get:
      operationId: list-executables
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListExecutablesResponseBody'
          description: OK
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
          description: Internal Server Error
  /api/press:
    post:
      operationId: press
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostPressRequestBody'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: OK
        "422":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
          description: Unprocessable Entity
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
          description: Internal Server Error
servers:
  - description: Site
    url: ""
