name: push

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: read
  id-token: write
  packages: write

defaults:
  run:
    shell: bash

jobs:

  detect-changes:
    uses: ./.github/workflows/detect-changes.yml
    secrets: inherit

  version-update:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.bot-change == 'false' && (needs.detect-changes.outputs.update-manager == 'true' || needs.detect-changes.outputs.workflows == 'true') }}
    uses: ./.github/workflows/version-update.yml
    secrets: inherit

  build-and-push:
    needs: detect-changes
    uses: ./.github/workflows/docker-build.yml
    if: ${{ needs.detect-changes.outputs.bot-change == 'true' }}
    with:
      push: true
    secrets: inherit
